spring:
  application:
    name: demo-datasource-hikari-single-app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root

    hikari:
      minimum-idle: 20 #池中最小的空闲连接数，默认为10个
      maximum-pool-size: 20 # 池中最大连接数， 包括空闲和使用中的连接，默认为10个
server:
  port: 9002